environment:
  username:
    secure: tcQSn721ejWM/6OctqLR2hP9PPIh8G3ea2TMmmO0WZ4=
  password:
    secure: KGlcZrCbXtRX46QVAskRFi2BaEVb4BeDFSDcke1Aa1c=

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:username):$env:password@appharbor.com`n"
  - git remote add appharbor https://github.com/Famintus/WebPlataform.git
  - git push appharbor master